name: "links-template-render"
description: "An action to render links configuration files into html with Go"

inputs:
  template:
    description: "Path of the template file to render in the repo"
    required: true
    default: "index.html.tmpl"
  values:
    description: "Path of the values file to render with in the repo"
    required: true
    default: "links.yaml"
  outputFile:
    description: "File to output rendered content to"
    required: false
    default: "index.html"

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.template }}
    - ${{ inputs.values }}
    - ${{ inputs.outputFile }}